# Generated by Django 3.1.7 on 2021-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient', models.CharField(max_length=50, verbose_name="engriedent's inventory")),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('ingridient', models.ManyToManyField(to='apimain.Ingridients')),
            ],
        ),
    ]
