# Generated by Django 3.1.7 on 2021-11-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ingridient',
        ),
        migrations.CreateModel(
            name='IngridientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingridients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimain.ingridients')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimain.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='all_ingridient',
            field=models.ManyToManyField(through='apimain.IngridientQuantity', to='apimain.Ingridients', verbose_name='all ingriedients'),
        ),
    ]
