# Generated by Django 3.1.7 on 2021-11-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimain', '0002_auto_20211107_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='ingridient_quantities',
            new_name='all_ingridient',
        ),
    ]
