# Generated by Django 3.1.7 on 2021-11-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimain', '0004_auto_20211103_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngridientQuantity',
            new_name='IngredientQuantity',
        ),
        migrations.RenameModel(
            old_name='Ingridients',
            new_name='Inventory',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='ingridient',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
